# Generated by Django 2.0.4 on 2018-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_visa', models.CharField(choices=[('1', 'No visa required'), ('2', 'Visa on arrival'), ('3', 'No visa required, if Schengen visa'), ('4', 'No visa required, if UK visa'), ('5', 'No visa required, if US visa'), ('6', 'Simple online application'), ('7', 'Fuck all visa process')], default=7, max_length=2)),
            ],
        ),
    ]
