# Generated by Django 2.0.4 on 2018-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_image',
            field=models.ImageField(blank=True, default='.images/default.jpg', null=True, upload_to='country_image'),
        ),
    ]
