# Generated by Django 2.0.4 on 2018-04-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0002_country_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/country_images'),
        ),
    ]
