# Generated by Django 2.0.4 on 2018-04-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0003_auto_20180407_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_image',
        ),
    ]
