# Generated by Django 2.0.4 on 2018-04-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0006_auto_20180408_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(default='../default.jpg', upload_to='media'),
        ),
    ]
