# Generated by Django 2.0.4 on 2018-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0007_auto_20180408_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_visa',
        ),
        migrations.AddField(
            model_name='country',
            name='country_visa',
            field=models.ManyToManyField(to='visa_app.VisaChoices'),
        ),
    ]
